### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by jazerix** [simonnilsson/react-file-icons#1]
Hi Simonnilsson!

Thank you for your work 😄 

Any chance I can get you to pull in some of the latest icons from the material icon theme?  It seems to be missing PHP 

Cheers!

**Comment by simonnilsson** [comment]
Hi @jazerix, I have made a new release adding 35 new icons (v2.3.0). The PHP icon is still not included however, this is due to it not being present in the icon definitions file of the material icon theme even though the icon itself is there. I might look into another way of extracting the icons that is not dependent on the definition file, this might take some time however.

Will keep this issue open.

**Comment by simonnilsson** [comment]
Version 2.4.0 now includes the PHP icon among other improvements.

**Comment by jazerix** [comment]
Wow, that was fast! Thanks a ton :D I hope it wasn't too much of a hassle!
